INSERT INTO tb_usuario (nome, tipo_permissao, email, senha, ativo)
VALUES ('Abraão', 'ADMIN', 'abraao@apidev.com', 'senha123', TRUE),
       ('Sara', 'GERENTE', 'sara@apidev.com', 'senha456', TRUE),
       ('Moisés', 'OPERADOR', 'moises@apidev.com', 'senha789', TRUE),
       ('Maria', 'VISITANTE', 'maria@apidev.com', 'senha101', TRUE),
       ('Davi', 'ADMIN', 'davi@apidev.com', 'senha112', TRUE),
       ('Rute', 'GERENTE', 'rute@apidev.com', 'senha131', TRUE),
       ('Isaque', 'OPERADOR', 'isaque@apidev.com', 'senha414', TRUE),
       ('Ester', 'VISITANTE', 'ester@apidev.com', 'senha151', TRUE),
       ('Noé', 'ADMIN', 'noe@apidev.com', 'senha616', TRUE),
       ('Rebeca', 'GERENTE', 'rebeca@apidev.com', 'senha717', TRUE),
       ('João', 'OPERADOR', 'joao@apidev.com', 'senha181', TRUE),
       ('Ana', 'VISITANTE', 'ana@apidev.com', 'senha919', TRUE),
       ('José', 'ADMIN', 'jose@apidev.com', 'senha202', TRUE),
       ('Isabel', 'GERENTE', 'isabel@apidev.com', 'senha121', TRUE),
       ('Daniel', 'OPERADOR', 'daniel@apidev.com', 'senha222', TRUE),
       ('Samuel', 'VISITANTE', 'samuel@apidev.com', 'senha333', TRUE),
       ('Jonas', 'ADMIN', 'jonas@apidev.com', 'senha444', TRUE),
       ('Jacó', 'GERENTE', 'jaco@apidev.com', 'senha555', TRUE),
       ('Elias', 'OPERADOR', 'elias@apidev.com', 'senha666', TRUE),
       ('Eva', 'VISITANTE', 'eva@apidev.com', 'senha777', TRUE);